# -*- coding: utf-8 -*-
"""Reinforcement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16d8SuF_2lLdy4DuViIdOpivYYlSnp_l9
"""

pip install stable-baselines3[extra] gym

import gymnasium as gym

env = gym.make("CartPole-v1", render_mode="human")

env.reset()

print("Sample action:", env.observation_space.shape)

print("sample observation:", env.observation_space.sample())

env.close()



for step in range(200):
  env.render()
  obs, reward, done, shortened, info = env.step(env.action_space.sample())
  print(reward)
  if done:
    env.reset()
    break